const projects = [
    {
        id: 1,
        title: "Express With File Storage",
        description: "First try using express with file storage.",
        long_description: "Using Express, this project can send and retrieve information about favorite foods using a text file for storage.",
        technologies: "Express routes were used to get and send data to a text document.",
        contributions: "I worked on this project alone. I used a tutorial provided by the instructor to get a base project up and running and then modified it to meet the requirements of the assignment.",
        image: "../../images/expressFileStorage1.png",
        image2: "../../images/expressFileStorage2.png",
        link: "/project/1",
        github: 'https://github.com/SamuelMHunter/samuelmhunter.github.io/tree/main/expressWithFileStorage',
    },
    {
        id: 2,
        title: "Four In a Row Game",
        description: "A four in a row game for two players.",
        long_description: "This project was my first time using React. It is a four in a row game that two players may play.",
        technologies: "This project uses React.",
        contributions: "I worked on this one on my own using the Tic-Tac-Toe game we made in class as an example to expand upon.",
        image: "../../images/fourInARow1.png",
        image2: "../../images/fourInARow2.png",
        link: "/project/2",
        github: 'https://github.com/SamuelMHunter/samuelmhunter.github.io/tree/main/fourInARow',    },
    {
        id: 3,
        title: "Express With Mongo",
        description: "Simple backend for a banking app.",
        long_description: "This project does not include a frontend. It uses Mongo to store user accounts. Express handles the interactions with Mongo.",
        technologies: "I used Express and Mongo.",
        contributions: "I worked on this project alone. I created a similar application in class, which I could then use to refer back to when completing this project.",
        image: "../../images/expressWithMongo1.png",
        image2: "../../images/expressWithMongo2.png",
        link: "/project/3",
        github: 'https://github.com/SamuelMHunter/samuelmhunter.github.io/tree/main/expressMongoBackend/backend',    },
    {
        id: 4,
        title: "Mern Sessions",
        description: "Simple banking app with session tracking.",
        long_description: "This project expanded on the previous one. It can now track sessions and also includes a simple frontend.",
        technologies: "I used Mongo, Express, and React for this one. Also inlcuded session tracking.",
        contributions: "I worked on this project on my own. I did use a tutorial provided by the professor to get started.",
        image: "../../images/mernSessions1.png",
        image2: "../../images/mernSessions2.png",
        link: "/project/4",
        github: 'https://github.com/SamuelMHunter/samuelmhunter.github.io/tree/main/mernSessions',    },
    {
        id: 5,
        title: "Hangman Game",
        description: "First group project. A hangman game.",
        long_description: "This hangman game was a group project incorporating all parts of the MERN stack.",
        technologies: "We used Mongo, Express and React. We also used bootstrap to help with design.",
        contributions: "For this project, I worked primarily on the win screen on the frontend.",
        image: "../../images/hangman1.png",
        image2: "../../images/hangman2.png",
        link: "/project/5",
        github: 'https://github.com/SamuelMHunter/samuelmhunter.github.io/tree/main/hangmanGame',    },
    {
        id: 6,
        title: "Banking App",
        description: "Second group project. A full fledged bank app.",
        long_description: "This bank app allows for transfers between users. Also has an employee dashboard exclusive for employee users.",
        technologies: "We used Mongo, Express and React. We also used bootstrap to help with the design.",
        contributions: "I worked on tracking the date and time transactions are made. This involved both frontend and backend work to pull off. I also created a backend route to return the transaction history of all users for employee use. I was responsible for adding error messages to pages where unexpected user input could be made. I created a frontend page for displaying individual transactions for a user. Finally, I fixed formatting issues with the contact information at the top of the page.",
        image: "../../images/bankingApp1.png",
        image2: "../../images/bankingApp2.png",
        link: "/project/6",
        github: 'https://github.com/SamuelMHunter/samuelmhunter.github.io/tree/main/CS3750-Banking-Application',    },
];

export default projects;