const projects = [
    {
        id: 1,
        title: "Express With File Storage",
        description: "First try using express with file storage.",
        long_description: "Using Express, this project can send and retrieve information about favorite foods using a text file for storage.",
        technologies: "Express routes were used to get and send data to a text document.",
        contributions: "I worked on this project alone. I used a tutorial provided by the instructor to get a base project up and running and then modified it to meet the requirements of the assignment.",
        image: "../../images/expressFileStorage1.png",
        image2: "../../images/expressFileStorage2.png",
        link: "/project/1",
        github: 'https://github.com/SamuelMHunter/samuelmhunter.github.io/tree/main/expressWithFileStorage',
    },
    {
        id: 2,
        title: "Four In a Row Game",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/fourInARow1.png",
        image2: "../../images/fourInARow2.png",
        link: "/project/2",
        github: 'https://github.com/',    },
    {
        id: 3,
        title: "Express With Mongo",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/expressWithMongo1.png",
        image2: "../../images/expressWithMongo2.png",
        link: "/project/3",
        github: 'https://github.com/',    },
    {
        id: 4,
        title: "Mern Sessions",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/mernSessions1.png",
        image2: "../../images/mernSessions2.png",
        link: "/project/4",
        github: 'https://github.com/',    },
    {
        id: 5,
        title: "Hangman Game",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/hangman1.png",
        image2: "../../images/hangman2.png",
        link: "/project/5",
        github: 'https://github.com/',    },
    {
        id: 6,
        title: "Banking App",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/bankingApp1.png",
        image2: "../../images/bankingApp2.png",
        link: "/project/6",
        github: 'https://github.com/',    },
];

export default projects;