const projects = [
    {
        id: 1,
        title: "Express With File Storage",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/expressFileStorage1.png",
        image2: "../../images/expressFileStorage2.png",
        link: "/project/1",
        github: 'https://github.com/',
    },
    {
        id: 2,
        title: "Four In a Row Game",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/fourInARow1.png",
        image2: "../../images/fourInARow2.png",
        link: "/project/2",
        github: 'https://github.com/',    },
    {
        id: 3,
        title: "Express With Mongo",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/expressWithMongo1.png",
        image2: "../../images/expressWithMongo2.png",
        link: "/project/3",
        github: 'https://github.com/',    },
    {
        id: 4,
        title: "Mern Sessions",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/mernSessions1.png",
        image2: "../../images/mernSessions2.png",
        link: "/project/4",
        github: 'https://github.com/',    },
    {
        id: 5,
        title: "Hangman Game",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/hangman1.png",
        image2: "../../images/hangman2.png",
        link: "/project/5",
        github: 'https://github.com/',    },
    {
        id: 6,
        title: "Banking App",
        description: "Short project description",
        long_description: "Each project should have about a full page of description for the project",
        technologies: "An explanation of the technologies used, including one or more technical challenges you solved.",
        contributions: "Explanation of your particular contributions.",
        image: "../../images/bankingApp1.png",
        image2: "../../images/bankingApp2.png",
        link: "/project/6",
        github: 'https://github.com/',    },
];

export default projects;